### ISSUE TITLE
.NET Cli output both TeamCity test messages and TRX file for SonarQube.

### ISSUE THREAD

**Issue by GrayPockets** [JetBrains/teamcity-dotnet-plugin#150]
When using the dotnet .CLI, we can't use a parameter like "--logger trx;LogFileName=results.trx" to output a test result file (for eventual pickup via SonarQube).

Please provide a way to output a test file.

**Comment by joergsesterhenn** [comment]
I tried using "--logger trx;LogFileName=results.trx" too. Why is this not working in Teamcity? 
I need the reports to hand them to sonarqube - is there another way to do this?

**Comment by GrayPockets** [comment]
@joergsesterhenn
When I reviewed my logs, I came to the understanding that the dotnet .CLI runner pipes the results into a specialized logger that disallows any other loggers so that it can send the results to TeamCity.

As a work-around I had to switch to command line to create the file for SonarQube and use the "XML Report Processing" build feature to import the unit test results back into TeamCity.

**Comment by joergsesterhenn** [comment]
Thanks, will try this too.

**Comment by mchechulnikov** [comment]
Using `--logger:trx` in command line parameters is now available since TeamCity 2023.05.1 ([the commit](https://github.com/JetBrains/teamcity-dotnet-plugin/commit/51aa69addc72eaa5a4a453dd0b4fdb5168c5a216)).

Previously, it wasn't available because of https://github.com/microsoft/vstest/issues/2368

Closing the issue for now. Please, feel free to reopen, if you need help
