### ISSUE TITLE
New plugin download?

### ISSUE THREAD

**Issue by fubar-coder** [JetBrains/teamcity-dotnet-plugin#167]
Is it possible to get the current version of the plugin as installable ZIP file for TeamCity 2023.05.4? I really need the VS2022/MSBuild 17 support, but TeamCity uses an outdated version of this plugin and I wasn't able to find any hints about creating a plugin ZIP from the build of this repository.

**Comment by mchechulnikov** [comment]
Hi @fubar-coder , 

Sorry for late response.

You could build the plugin by yourself using Java 11, for example
* pull the repository
* run  `./gradlew clean build` in the root of the repository 
* you can find the distribution as installable .zip in `./plugin-dotnet-server/build/distributions/dotnet.zip`

However, unfortunately, it's not possible to build the version from the active branches compatible with `2023.05.x` since it depends on corresponding changes in TeamCity core part a lot. 

Could you please advise, on which runner you need to get VS2022/MSBuild 17 support? It looks like these versions should be available in .NET runner.

**Comment by mchechulnikov** [comment]
Closing the issue for now. Please feel free to reopen it if you need help.
